package:
  name: rdrpcatch
  version: '1.0.0'

source:
  path: .
  exclude:
    - .gitignore
    - .git
    - .idea


build:
  number: 2
  script: |
    # First install the package itself with pip
    $PYTHON -m pip install . --no-deps -vv

  entry_points:
    - rdrpcatch = rdrpcatch.cli.args:cli
  # Ensure pip dependencies are preserved
  preserve_egg_dir: True

requirements:
  host:
    - python =3.12
    - pip
    - setuptools

  run:
    # Conda dependencies
    - python=3.12
    - mmseqs2=16.747c6
    - seqkit=2.9.0
    - matplotlib=3.10.0
    - biopython=1.85
    - upsetplot=0.9.0
    - pandas=2.2.3
    - pyhmmer=0.11.0
    - rich=13.9.4
    - rich-click=1.8.6
    - seaborn=0.13.2

test:
    commands:
        - rdrpcatch --help

about:
  home: https://github.com/dimitris-karapliafis/RdRpCATCH
  summary: RNA virus RdRp sequence scanner